//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace razorMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class state
    {
        public int stid { get; set; }
        public Nullable<int> cntry_id { get; set; }
        public string sname { get; set; }
    }
}
